import { useState, useEffect } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { BookOpen, Calendar, Clock, ChevronRight, X, Sparkles } from "lucide-react"
import { api } from "@/services/api"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"

export function Reports() {
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [selectedReport, setSelectedReport] = useState<any | null>(null)

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const response = await api.get("/reports")
        setReports(response.data)
      } catch (err) {
        console.error("Failed to fetch reports", err)
      } finally {
        setLoading(false)
      }
    }
    fetchReports()
  }, [])

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
      <div className="mx-auto max-w-6xl">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-2">My Reports</h1>
            <p className="text-muted-foreground">View and manage your generated literature reviews.</p>
          </div>
          <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary border border-primary/20 text-sm font-medium">
            <Sparkles className="h-4 w-4" />
            {reports.length} Total Reports
          </div>
        </div>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3].map(i => (
              <div key={i} className="h-48 rounded-xl bg-secondary/50 animate-pulse border border-border/50" />
            ))}
          </div>
        ) : reports.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-center bg-card rounded-2xl border border-border/50 shadow-sm">
            <div className="h-16 w-16 rounded-full bg-primary/10 flex items-center justify-center mb-6">
              <BookOpen className="h-8 w-8 text-primary" />
            </div>
            <h3 className="text-xl font-semibold mb-2">No reports generated yet</h3>
            <p className="text-muted-foreground max-w-sm mb-6">
              Head over to the Literature Review section to generate your first Multi-Agent AI report.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {reports.map((report, idx) => (
              <motion.div
                key={report._id || idx}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: idx * 0.1 }}
                onClick={() => setSelectedReport(report)}
                className="group flex flex-col rounded-2xl border border-border/50 bg-card p-6 shadow-sm hover:border-primary/50 hover:shadow-md transition-all cursor-pointer relative overflow-hidden"
              >
                {/* Subtle gradient hover effect */}
                <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                
                <div className="relative z-10">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="h-10 w-10 rounded-xl bg-primary/20 flex items-center justify-center border border-primary/20">
                      <BookOpen className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-lg line-clamp-1">{report.topic}</h3>
                      <div className="flex items-center gap-1 text-xs text-muted-foreground mt-0.5">
                        <Calendar className="h-3 w-3" />
                        {new Date(report.created_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                  
                  <p className="text-sm text-muted-foreground line-clamp-3 mb-6 flex-1">
                    {(report.content || "").replace(/[#*]/g, '')}
                  </p>
                  
                  <div className="mt-auto flex items-center justify-between pt-4 border-t border-border/50">
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" />
                      Generated by Llama-3.3
                    </div>
                    <ChevronRight className="h-4 w-4 text-primary group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}

        {/* Full Screen Report Viewer Modal */}
        <AnimatePresence>
          {selectedReport && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 lg:p-12">
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setSelectedReport(null)}
                className="absolute inset-0 bg-background/80 backdrop-blur-sm"
              />
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 20 }}
                className="relative w-full max-w-4xl h-full flex flex-col rounded-2xl border border-border/50 bg-background shadow-2xl z-10 overflow-hidden"
              >
                <div className="flex items-center justify-between p-4 sm:p-6 border-b border-border/50 bg-card/50 backdrop-blur-xl">
                  <div>
                    <h2 className="text-xl sm:text-2xl font-bold tracking-tight">{selectedReport.topic}</h2>
                    <p className="text-sm text-muted-foreground mt-1">Generated on {new Date(selectedReport.created_at).toLocaleDateString()}</p>
                  </div>
                  <button
                    onClick={() => setSelectedReport(null)}
                    className="rounded-full p-2 text-muted-foreground hover:bg-secondary hover:text-foreground transition-colors"
                  >
                    <X className="h-5 w-5" />
                  </button>
                </div>
                
                <div className="flex-1 overflow-y-auto p-6 sm:p-10 prose prose-sm sm:prose-base dark:prose-invert prose-headings:text-foreground prose-a:text-primary max-w-none bg-background">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {selectedReport.content || ""}
                  </ReactMarkdown>
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}
